#!/usr/bin/env python3
import re
import csv
from pathlib import Path

REPORT = Path("reports/full_coverage_step6.txt")
CSV_OUT = Path("reports/coverage_summary.csv")
MD_OUT = Path("reports/coverage_recommendations.md")

def pct(line):
    m = re.search(r"(\d+\.\d+)%", line)
    return float(m.group(1)) if m else None

def main():
    text = REPORT.read_text(errors="ignore").splitlines()

    rows = []
    current_inst = None
    current_metric = None
    recommendations = []

    for line in text:
        if line.startswith("=== Instance:"):
            current_inst = line.split("Instance:")[1].strip()

        if "Toggle Coverage:" in line:
            current_metric = "Toggle"
        elif "Branch Coverage:" in line:
            current_metric = "Branch"
        elif "Condition Coverage:" in line:
            current_metric = "Condition"
        elif "Statement Coverage:" in line:
            current_metric = "Statement"
        elif "FSM Coverage:" in line:
            current_metric = "FSM"
        elif "Assertion Coverage:" in line:
            current_metric = "Assertion"
        elif "Covergroup Coverage:" in line:
            current_metric = "Covergroup"

        if "Coverage" in line and "%" in line:
            value = pct(line)
            if value is not None and current_inst and current_metric:
                rows.append([current_inst, current_metric, value])

        if "***0***" in line or "not hit" in line:
            recommendations.append((current_inst, current_metric, line.strip()))

    CSV_OUT.parent.mkdir(exist_ok=True)

    with CSV_OUT.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["Instance", "Metric", "CoveragePercent"])
        writer.writerows(rows)

    with MD_OUT.open("w") as f:
        f.write("# AI-Assisted Coverage Analysis Report\n\n")
        f.write("## Summary\n\n")
        f.write("This report was generated by parsing QuestaSim coverage output and identifying low-coverage regions.\n\n")

        f.write("## Recommended Targeted Tests\n\n")

        for inst, metric, issue in recommendations:
            f.write(f"### Instance: `{inst}`\n")
            f.write(f"- Metric: `{metric}`\n")
            f.write(f"- Issue: `{issue}`\n")

            if "rd_ready" in issue:
                f.write("- Recommendation: Add read-response backpressure while `rd_valid` is high.\n\n")
            elif "wr_valid" in issue:
                f.write("- Recommendation: Add write command phase where command is accepted but write data is delayed.\n\n")
            elif "S_READ_CMD -> S_IDLE" in issue or "S_WRITE -> S_IDLE" in issue:
                f.write("- Recommendation: Add reset/abort tests while DDR FSM is in active non-IDLE states.\n\n")
            elif "rsp_pkt.rdata" in issue or "rd_data" in issue:
                f.write("- Recommendation: Add additional readback patterns to toggle remaining data bits.\n\n")
            elif "freq_ratio" in issue:
                f.write("- Recommendation: Add frequency-ratio mode tests if behavioral support is implemented.\n\n")
            else:
                f.write("- Recommendation: Review uncovered branch/toggle and add directed stimulus if functionally meaningful.\n\n")

    print("[AI-COV] Coverage summary written to:", CSV_OUT)
    print("[AI-COV] Recommendations written to:", MD_OUT)

if __name__ == "__main__":
    main()
